Repository go-shiori/shiori, pull requests merged in 2023-07, with the labels that each got.

#627 thumb image will be not accesable anymore if it is private fix #578
  internal/webserver/handler-ui.go
Labels: type:bug, component:backend, tag:waiting-for-assignee

#623 Initial Ebook support
  internal/core/ebook.go
  internal/core/ebook_test.go
  internal/core/processing.go
  internal/model/model.go
  internal/view/content.html
  internal/view/js/component/bookmark.js
  internal/view/js/page/base.js
  internal/view/js/page/home.js
  internal/webserver/handler-api.go
  internal/webserver/handler-ui.go
  internal/webserver/server.go
Labels: type:enhancement, component:frontend, component:backend, tag:waiting-for-assignee

#636 fix: prevent bookmark overwrite on archive download
  internal/webserver/handler-api.go
Labels: type:bug

#536 feat: add SHIORI_PG_SSLMODE
  docker-compose.yaml
  docs/Configuration.md
  internal/cmd/root.go
Labels: tag:waiting-for-assignee

#667 Proper SQLite default database and warn SHIORI_DBMS users
  internal/cmd/root.go
Labels: tag:no-stale
